name:                treeSearch
version:             0.1.0.0
github:              "githubuser/treeSearch"
license:             BSD3
author:              "Michal Parusinski"
maintainer:          "michal@parusinski.me"
copyright:           "2022 Michal Parusinski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mparusinski/treeSearch>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  treeSearch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - treeSearch

tests:
  treeSearch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - treeSearch
    - HUnit
